In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor

import warnings

warnings.filterwarnings('ignore')

%matplotlib inline

sns.set(color_codes=True)

In [19]:
data = pd.read_excel(
    io='data/stock portfolio performance data set.xlsx',
    sheet_name='all period',
    header=1,
    usecols='A:S',
    index_col=0
)

In [9]:
data.head()

,Large B/P,Large ROE,Large S/P,Large Return Rate in the last quarter,Large Market Value,Small systematic Risk,Annual Return,Excess Return,Systematic Risk,Total Risk,Abs. Win Rate,Rel. Win Rate,Annual Return.1,Excess Return.1,Systematic Risk.1,Total Risk.1,Abs. Win Rate.1,Rel. Win Rate.1
ID,,,,,,,,,,,,,,,,,,
1,1.0,0.0,0.0,0.0,0.0,0.0,0.139,0.010,1.33,0.149,0.663,0.525,0.531875,0.478116,0.738015,0.800000,0.52,0.411765
2,0.0,1.0,0.0,0.0,0.0,0.0,0.143,0.010,1.17,0.108,0.663,0.650,0.549712,0.487595,0.571579,0.412231,0.52,0.764706
3,0.0,0.0,1.0,0.0,0.0,0.0,0.173,0.018,1.30,0.144,0.638,0.513,0.692625,0.629895,0.703051,0.756879,0.44,0.376471
4,0.0,0.0,0.0,1.0,0.0,0.0,0.096,-0.002,1.39,0.144,0.613,0.475,0.324351,0.255634,0.800000,0.756046,0.36,0.270588
5,0.0,0.0,0.0,0.0,1.0,0.0,0.096,0.001,1.04,0.087,0.725,0.538,0.326615,0.306501,0.432452,0.209289,0.72,0.447059

In [13]:
X = data.iloc[:,0:6]
X.head()

,Large B/P,Large ROE,Large S/P,Large Return Rate in the last quarter,Large Market Value,Small systematic Risk
ID,,,,,,
1,1.0,0.0,0.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0
4,0.0,0.0,0.0,1.0,0.0,0.0
5,0.0,0.0,0.0,0.0,1.0,0.0

In [16]:
y = data['Systematic Risk.1']
y.head()

ID
1    0.738015
2    0.571579
3    0.703051
4    0.800000
5    0.432452
Name: Systematic Risk.1, dtype: float64

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [23]:
knn = KNeighborsRegressor(n_neighbors=5).fit(X_train, y_train)
knn.score(X_train, y_train)

0.5696865565153362

In [24]:
knn.score(X_test, y_test)

0.41904439473402266

In [27]:
n_values = [1, 3, 5, 7, 9, 11]

for n in n_values:
    knn = KNeighborsRegressor(n_neighbors=n).fit(X_train, y_train)
    print('k={0}'.format(n))
    print('train score: {0:.3f}'.format(knn.score(X_train, y_train)))
    print('test score: {0:.3f}'.format(knn.score(X_test, y_test)))

k=1
train score: 1.000
test score: 0.273
k=3
train score: 0.774
test score: 0.362
k=5
train score: 0.570
test score: 0.419
k=7
train score: 0.495
test score: 0.394
k=9
train score: 0.377
test score: 0.308
k=11
train score: 0.303
test score: 0.257